/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PoptavkaRouteImport } from './routes/poptavka'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as SortimentRouteImport } from './routes/sortiment'
import { Route as SortimentSlugRouteImport } from './routes/sortiment.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PoptavkaRoute = PoptavkaRouteImport.update({
  id: '/poptavka',
  path: '/poptavka',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const SortimentRoute = SortimentRouteImport.update({
  id: '/sortiment',
  path: '/sortiment',
  getParentRoute: () => rootRouteImport,
} as any)
const SortimentSlugRoute = SortimentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SortimentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/poptavka': typeof PoptavkaRoute
  '/reference': typeof ReferenceRoute
  '/sortiment': typeof SortimentRouteWithChildren
  '/sortiment/$slug': typeof SortimentSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/poptavka': typeof PoptavkaRoute
  '/reference': typeof ReferenceRoute
  '/sortiment': typeof SortimentRouteWithChildren
  '/sortiment/$slug': typeof SortimentSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/poptavka': typeof PoptavkaRoute
  '/reference': typeof ReferenceRoute
  '/sortiment': typeof SortimentRouteWithChildren
  '/sortiment/$slug': typeof SortimentSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/poptavka'
    | '/reference'
    | '/sortiment'
    | '/sortiment/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/poptavka'
    | '/reference'
    | '/sortiment'
    | '/sortiment/$slug'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/poptavka'
    | '/reference'
    | '/sortiment'
    | '/sortiment/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  PoptavkaRoute: typeof PoptavkaRoute
  ReferenceRoute: typeof ReferenceRoute
  SortimentRoute: typeof SortimentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poptavka': {
      id: '/poptavka'
      path: '/poptavka'
      fullPath: '/poptavka'
      preLoaderRoute: typeof PoptavkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sortiment': {
      id: '/sortiment'
      path: '/sortiment'
      fullPath: '/sortiment'
      preLoaderRoute: typeof SortimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sortiment/$slug': {
      id: '/sortiment/$slug'
      path: '/$slug'
      fullPath: '/sortiment/$slug'
      preLoaderRoute: typeof SortimentSlugRouteImport
      parentRoute: typeof SortimentRoute
    }
  }
}

interface SortimentRouteChildren {
  SortimentSlugRoute: typeof SortimentSlugRoute
}

const SortimentRouteChildren: SortimentRouteChildren = {
  SortimentSlugRoute: SortimentSlugRoute,
}

const SortimentRouteWithChildren = SortimentRoute._addFileChildren(
  SortimentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  PoptavkaRoute: PoptavkaRoute,
  ReferenceRoute: ReferenceRoute,
  SortimentRoute: SortimentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
